// utils/gemini.js
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY); // use .env
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

/**
 * Generate interview Q&A in JSON format
 * @param {string} role - The job role (e.g., "Full Stack Developer")
 * @param {string} description - The job role (e.g., "Full Stack Developer")
 * @param {string} expirience - The job role (e.g., "Full Stack Developer")
 * @param {number} count - Number of questions
 * @returns {Promise<Array<{question: string, answer: string}>>}
 * 
 * @param {string} question - "the question feild that was generated by the ai"
 * @param {string} userAnswer - "the answer feild that was given by user"
 */
export async function generateInterviewQA(role, description, expirience, count = 5) {
  const prompt = `
  Act as an interviewer for a ${role} position.
  With the tech stack  ${description} having ${expirience} year of expirience.
  Generate ${count} interview questions with strong sample answers.
  Respond ONLY in pure JSON array format like this:
  [
    {"question": "Question text", "answer": "Answer text"},
    ...
  ]
  `;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();

    // Try parsing JSON safely
    const match = text.match(/\[([\s\S]*)\]/); // extract array
    if (match) {
      return JSON.parse(match[0]);
    }

    throw new Error("No valid JSON found in response");
  } catch (err) {
    console.error("Gemini JSON parse error:", err);
    return [];
  }
}
export async function generateQAFeedback(question,userAnswer) {
  const feedbackPrompt = `
  Question: ${question} , User Answer:  ${userAnswer} , Depending on the Question and User Answer .Please give me rating and also the feedback for area of imporovement if any in just 3 to 5 line to imporove it.
  Respond ONLY in pure JSON array format like this:
  [
    {"rating": "rating in number 1 - 5", "feedback": "feedback text 3 to 5 line"},
    ...
  ]
  `;

  try {
    const result = await model.generateContent(feedbackPrompt);
    const text = result.response.text();

    // Try parsing JSON safely
    const match = text.match(/\[([\s\S]*)\]/); // extract array
    if (match) {
      return JSON.parse(match[0]);
    }

    throw new Error("No valid JSON found in response");
  } catch (err) {
    console.error("Gemini JSON parse error:", err);
    return [];
  }
}
